// <auto-generated />
using System;
using CRUD_SQLSERVER.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_SQLSERVER.Migrations
{
    [DbContext(typeof(PetShopContext))]
    [Migration("20220607140717_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CRUD_SQLSERVER.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"), 1L, 1);

                    b.Property<bool>("Castrado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Nascimento");

                    b.Property<int>("Especie")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PlanoId")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.HasIndex("PlanoId");

                    b.ToTable("Tbl_Animal");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.AnimalVeterinario", b =>
                {
                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("int");

                    b.HasKey("AnimalId", "VeterinarioId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Tbl_Animal_Veterinario");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.ContratoTrabalho", b =>
                {
                    b.Property<int>("ContratoTrabalhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContratoTrabalhoId"), 1L, 1);

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("date")
                        .HasColumnName("Dt_Contratacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ContratoTrabalhoId");

                    b.ToTable("Tbl_Contrato_Trabalho");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.Plano", b =>
                {
                    b.Property<int>("PlanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanoId"), 1L, 1);

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanoId");

                    b.ToTable("Tbl_Plano");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.Veterinario", b =>
                {
                    b.Property<int>("VeterinarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeterinarioId"), 1L, 1);

                    b.Property<int>("ContratoTrabalhoId")
                        .HasColumnType("int");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("VeterinarioId");

                    b.HasIndex("ContratoTrabalhoId");

                    b.ToTable("Tbl_Veterinario");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.Animal", b =>
                {
                    b.HasOne("CRUD_SQLSERVER.Models.Plano", "Plano")
                        .WithMany("Animais")
                        .HasForeignKey("PlanoId");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.AnimalVeterinario", b =>
                {
                    b.HasOne("CRUD_SQLSERVER.Models.Animal", "Animal")
                        .WithMany("AnimaisVeterinarios")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUD_SQLSERVER.Models.Veterinario", "Veterinario")
                        .WithMany("AnimaisVeterinarios")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.Veterinario", b =>
                {
                    b.HasOne("CRUD_SQLSERVER.Models.ContratoTrabalho", "ContratoTrabalho")
                        .WithMany()
                        .HasForeignKey("ContratoTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContratoTrabalho");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.Animal", b =>
                {
                    b.Navigation("AnimaisVeterinarios");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.Plano", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("CRUD_SQLSERVER.Models.Veterinario", b =>
                {
                    b.Navigation("AnimaisVeterinarios");
                });
#pragma warning restore 612, 618
        }
    }
}
